In [9]:
import emat
import os
import pandas as pd
from emat.util.loggers import timing_log
from emat.analysis import feature_scores

emat.require_version('0.5.1')

emat 0.6.0, plotly 6.1.2

In [10]:
#!pip install openpyxl

In [11]:
# Update the path as needed.
os.chdir(".")
model_results_dir = "AllResults_05202025"

In [12]:
scope = emat.Scope('EMAT/PAG/PAG_EMAT_scope_final.yml')

In [13]:
scope.info()

name: PAG EMAT
domain: PAG EMAT
desc: PAG EMAT
uncertainties:
  HH_EMP_Growth = 0.0 to 1.0
  HH_EMP_Distribution = 0.0 to 1.0
  AV_Rates = 0.0 to 1.0
  EV_Rates = 0.0 to 1.0
  Teleworking = 0.0 to 0.4
  Heavy_Medium_Truck_Travel = 0.0 to 1.0
  Ecommerce = 0.0 to 0.2
levers:
  Transit_Headways = 0.5 to 2.0
  Transit_Service_Expansion = categorical
  Roadway_Capacity_Improvement = categorical
  Road_User_Fee = 0.0 to 0.1
  Incentives_Special_AreaPop = 0.0 to 0.5
measures:
  Regional Auto Trips
  Regional Bike Trips
  Regional School Bus Trips
  Regional Taxi Trips
  Regional Transit Trips
  Regional Walk Trips
  Auto Mode Share
  Bike Mode Share
  School Bus Mode Share
  Taxi Mode Share
  Transit Mode Share
  Walk Mode Share
  Auto PMT
  Bike PMT
  SchoolBus PMT
  Taxi PMT
  Transit PMT
  Walk PMT
  Auto PMT Ratio
  Bike PMT Ratio
  School Bus PMT Ratio
  Taxi PMT Ratio
  Transit PMT Ratio
  Walk PMT Ratio
  Regional VMT
  Regional Congested VMT
  Regional Congested VMT PCT
  Regional VMT per Capita
  Regional VHT
  Regional VHTper Capita
  Average Commute Time by Auto
  Average Commute Time by Bike
  Average Commute Time by Taxi
  Average Commute Time by Transit
  Average Commute Time by Walk
  Average Transit Travel Time
  Highway Lane Miles of Freeways
  Highway Lane Miles of Parkways
  Highway Lane Miles of Major Arterial
  Highway Lane Miles of Minor Arterial
  Highway Lane Miles of Collector
  Highway Lane Miles of Ramps
  Highway Lane Miles of Frontage Road
  Rural Transit Miles Per Frequency - PK
  Regular Transit Miles Per Frequency - PK
  Express Transit Miles Per Frequency - PK
  CatTran Transit Miles Per Frequency - PK
  Regional BRT Transit Miles Per Frequency - PK
  Rural Transit Miles Per Frequency - OP
  Regular Transit Miles Per Frequency - OP
  Express Transit Miles Per Frequency - OP
  CatTran Transit Miles Per Frequency - OP
  Regional BRT Transit Miles Per Frequency - OP
  Regional Total Population
  Total Population within Quarter Mile
  Percentage of Population within Quarter Mile
  Regional Total DISADV Population
  DISADV Population within QuarterMile
  Percentage of DISADV Population within Quarter Mile
  Regional Total Jobs
  Total Jobs within Quarter Mile
  Percentage of Jobs within Quarter Mile
  Regional Total DISADV Jobs
  DISADV Jobs within QuarterMile
  Percentage of DISADV Jobs within Quarter Mile
  PK Average Transit Speed
  OP Average Transit Speed
  DY Average Transit Speed
  AM Travel Time Index
  PM Travel Time Index
  Regional Speed
  Auto Accessibility Off Peak
  Auto Accessibility Peak
  Auto Accessibility Off Peak within 30 Minutes
  Auto Accessibility Peak within 30 Minutes
  Auto Accessibility Percentage Off Peak within 30 Minutes
  Auto Accessibility Percentage Peak within 30 Minutes
  Transit Accessibility Off Peak
  Transit Accessibility Peak
  Transit Accessibility Off Peak within 45 Minutes
  Transit Accessibility Off Peak within 60 Minutes
  Transit Accessibility Off Peak within 90 Minutes
  Transit Accessibility Percentage Off Peak within 45 Minutes
  Transit Accessibility Percentage Off Peak within 60 Minutes
  Transit Accessibility Percentage Off Peak within 90 Minutes
  Transit Accessibility Peak within 45 Minutes
  Transit Accessibility Peak within 60 Minutes
  Transit Accessibility Peak within 90 Minutes
  Transit Accessibility Percetange Peak within 45 Minutes
  Transit Accessibility Percentage Peak within 60 Minutes
  Transit Accessibility Percentage Peak within 90 Minutes
  Disadvantage Zone Home to Work Commute Time by Auto 0
  Disadvantage Zone Home to Work Commute Time by Auto 1
  Disadvantage Zone Home to Work Commute Time by Bike 0
  Disadvantage Zone Home to Work Commute Time by Bike 1
  Disadvantage Zone Home to Work Commute Time by Taxi 0
  Disadvantage Zone Home to Work Commute Time by Taxi 1
  Disadvantage Zone Home to Work Commute Time by Transit 0
  Disadvantage Zone Home to Work Commute Time by Transit 1
  Disadvantage Zone Home to Work Commute Time by Walk 0
  Disadvantage Zone Home to Work Commute Time by Walk 1
  Disadvantage Zone Work to Home Commute Time by Auto 0
  Disadvantage Zone Work to Home Commute Time by Auto 1
  Disadvantage Zone Work to Home Commute Time by Bike 0
  Disadvantage Zone Work to Home Commute Time by Bike 1
  Disadvantage Zone Work to Home Commute Time by Taxi 0
  Disadvantage Zone Work to Home Commute Time by Taxi 1
  Disadvantage Zone Work to Home Commute Time by Transit 0
  Disadvantage Zone Work to Home Commute Time by Transit 1
  Disadvantage Zone Work to Home Commute Time by Walk 0
  Disadvantage Zone Work to Home Commute Time by Walk 1
  Disadvantage Zone Average Travel Time per Household by Auto 0
  Disadvantage Zone Average Travel Time per Household by Bike 0
  Disadvantage Zone Average Travel Time per Household by SchoolBus 0
  Disadvantage Zone Average Travel Time per Household by Taxi 0
  Disadvantage Zone Average Travel Time per Household by Transit 0
  Disadvantage Zone Average Travel Time per Household by Walk 0
  Disadvantage Zone Average Travel Time per Household by Auto 1
  Disadvantage Zone Average Travel Time per Household by Bike 1
  Disadvantage Zone Average Travel Time per Household by SchoolBus 1
  Disadvantage Zone Average Travel Time per Household by Taxi 1
  Disadvantage Zone Average Travel Time per Household by Transit 1
  Disadvantage Zone Average Travel Time per Household by Walk 1
  Disadvantage Zone Average Travel Time per Person by Auto 0
  Disadvantage Zone Average Travel Time per Person by Bike 0
  Disadvantage Zone Average Travel Time per Person by SchoolBus 0
  Disadvantage Zone Average Travel Time per Person by Taxi 0
  Disadvantage Zone Average Travel Time per Person by Transit 0
  Disadvantage Zone Average Travel Time per Person by Walk 0
  Disadvantage Zone Average Travel Time per Person by Auto 1
  Disadvantage Zone Average Travel Time per Person by Bike 1
  Disadvantage Zone Average Travel Time per Person by SchoolBus 1
  Disadvantage Zone Average Travel Time per Person by Taxi 1
  Disadvantage Zone Average Travel Time per Person by Transit 1
  Disadvantage Zone Average Travel Time per Person by Walk 1
  Disadvantage Zone Average Travel Distance per Household by Auto 0
  Disadvantage Zone Average Travel Distance per Household by Bike 0
  Disadvantage Zone Average Travel Distance per Household by SchoolBus 0
  Disadvantage Zone Average Travel Distance per Household by Taxi 0
  Disadvantage Zone Average Travel Distance per Household by Transit 0
  Disadvantage Zone Average Travel Distance per Household by Walk 0
  Disadvantage Zone Average Travel Distance per Household by Auto 1
  Disadvantage Zone Average Travel Distance per Household by Bike 1
  Disadvantage Zone Average Travel Distance per Household by SchoolBus 1
  Disadvantage Zone Average Travel Distance per Household by Taxi 1
  Disadvantage Zone Average Travel Distance per Household by Transit 1
  Disadvantage Zone Average Travel Distance per Household by Walk 1
  Disadvantage Zone Average Travel Distance per Person by Auto 0
  Disadvantage Zone Average Travel Distance per Person by Bike 0
  Disadvantage Zone Average Travel Distance per Person by SchoolBus 0
  Disadvantage Zone Average Travel Distance per Person by Taxi 0
  Disadvantage Zone Average Travel Distance per Person by Transit 0
  Disadvantage Zone Average Travel Distance per Person by Walk 0
  Disadvantage Zone Average Travel Distance per Person by Auto 1
  Disadvantage Zone Average Travel Distance per Person by Bike 1
  Disadvantage Zone Average Travel Distance per Person by SchoolBus 1
  Disadvantage Zone Average Travel Distance per Person by Taxi 1
  Disadvantage Zone Average Travel Distance per Person by Transit 1
  Disadvantage Zone Average Travel Distance per Person by Walk 1
  Average Commute Time by Auto of Income Quartile 1
  Average Commute Time by Bike of Income Quartile 1
  Average Commute Time by Taxi of Income Quartile 1
  Average Commute Time by Transit of Income Quartile 1
  Average Commute Time by Walk of Income Quartile 1
  Average Commute Time by Auto of Income Quartile 2
  Average Commute Time by Bike of Income Quartile 2
  Average Commute Time by Taxi of Income Quartile 2
  Average Commute Time by Transit of Income Quartile 2
  Average Commute Time by Walk of Income Quartile 2
  Average Commute Time by Auto of Income Quartile 3
  Average Commute Time by Bike of Income Quartile 3
  Average Commute Time by Taxi of Income Quartile 3
  Average Commute Time by Transit of Income Quartile 3
  Average Commute Time by Walk of Income Quartile 3
  Average Commute Time by Auto of Income Quartile 4
  Average Commute Time by Bike of Income Quartile 4
  Average Commute Time by Taxi of Income Quartile 4
  Average Commute Time by Transit of Income Quartile 4
  Average Commute Time by Walk of Income Quartile 4
  Average Commute Distance by Auto of Income Quartile 1
  Average Commute Distance by Bike of Income Quartile 1
  Average Commute Distance by Taxi of Income Quartile 1
  Average Commute Distance by Transit of Income Quartile 1
  Average Commute Distance by Walk of Income Quartile 1
  Average Commute Distance by Auto of Income Quartile 2
  Average Commute Distance by Bike of Income Quartile 2
  Average Commute Distance by Taxi of Income Quartile 2
  Average Commute Distance by Transit of Income Quartile 2
  Average Commute Distance by Walk of Income Quartile 2
  Average Commute Distance by Auto of Income Quartile 3
  Average Commute Distance by Bike of Income Quartile 3
  Average Commute Distance by Taxi of Income Quartile 3
  Average Commute Distance by Transit of Income Quartile 3
  Average Commute Distance by Walk of Income Quartile 3
  Average Commute Distance by Auto of Income Quartile 4
  Average Commute Distance by Bike of Income Quartile 4
  Average Commute Distance by Taxi of Income Quartile 4
  Average Commute Distance by Transit of Income Quartile 4
  Average Commute Distance by Walk of Income Quartile 4
  Disadvantage Zone Auto Accessibility Off Peak for Jobs 0
  Disadvantage Zone Auto Accessibility Off Peak for Jobs 1
  Disadvantage Zone Auto Accessibility Peak for Jobs 0
  Disadvantage Zone Auto Accessibility Peak for Jobs 1
  Disadvantage Zone Auto Accessibility Off Peak within 30 Minutes for Jobs 0
  Disadvantage Zone Auto Accessibility Off Peak within 30 Minutes for Jobs 1
  Disadvantage Zone Auto Accessibility Peak within 30 Minutes for Jobs 0
  Disadvantage Zone Auto Accessibility Peak within 30 Minutes for Jobs 1
  Disadvantage Zone Transit Accessibility Off Peak for Jobs 0
  Disadvantage Zone Transit Accessibility Off Peak for Jobs 1
  Disadvantage Zone Transit Accessibility Peak for Jobs 0
  Disadvantage Zone Transit Accessibility Peak for Jobs 1
  Disadvantage Zone Transit Accessibility Off Peak within 45 Minutes for Jobs 0
  Disadvantage Zone Transit Accessibility Off Peak within 45 Minutes for Jobs 1
  Disadvantage Zone Transit Accessibility Peak within 45 Minutes for Jobs 0
  Disadvantage Zone Transit Accessibility Peak within 45 Minutes for Jobs 1
  Disadvantage Zone Transit Accessibility Off Peak within 60 Minutes for Jobs 0
  Disadvantage Zone Transit Accessibility Off Peak within 60 Minutes for Jobs 1
  Disadvantage Zone Transit Accessibility Peak within 60 Minutes for Jobs 0
  Disadvantage Zone Transit Accessibility Peak within 60 Minutes for Jobs 1
  Disadvantage Zone Transit Accessibility Off Peak within 90 Minutes for Jobs 0
  Disadvantage Zone Transit Accessibility Off Peak within 90 Minutes for Jobs 1
  Disadvantage Zone Transit Accessibility Peak within 90 Minutes for Jobs 0
  Disadvantage Zone Transit Accessibility Peak within 90 Minutes for Jobs 1
  Disadvantage Zone Auto Accessibility Off Peak for Basic Needs 0
  Disadvantage Zone Auto Accessibility Off Peak for Basic Needs 1
  Disadvantage Zone Auto Accessibility Peak for Basic Needs 0
  Disadvantage Zone Auto Accessibility Peak for Basic Needs 1
  Disadvantage Zone Auto Accessibility Off Peak within 30 Minutes for Basic Needs 0
  Disadvantage Zone Auto Accessibility Off Peak within 30 Minutes for Basic Needs 1
  Disadvantage Zone Auto Accessibility Peak within 30 Minutes for Basic Needs 0
  Disadvantage Zone Auto Accessibility Peak within 30 Minutes for Basic Needs 1
  Disadvantage Zone Transit Accessibility Off Peak for Basic Needs 0
  Disadvantage Zone Transit Accessibility Off Peak for Basic Needs 1
  Disadvantage Zone Transit Accessibility Peak for Basic Needs 0
  Disadvantage Zone Transit Accessibility Peak for Basic Needs 1
  Disadvantage Zone Transit Accessibility Off Peak within 45 Minutes for Basic Needs 0
  Disadvantage Zone Transit Accessibility Off Peak within 45 Minutes for Basic Needs 1
  Disadvantage Zone Transit Accessibility Peak within 45 Minutes for Basic Needs 0
  Disadvantage Zone Transit Accessibility Peak within 45 Minutes for Basic Needs 1
  Disadvantage Zone Transit Accessibility Off Peak within 60 Minutes for Basic Needs 0
  Disadvantage Zone Transit Accessibility Off Peak within 60 Minutes for Basic Needs 1
  Disadvantage Zone Transit Accessibility Peak within 60 Minutes for Basic Needs 0
  Disadvantage Zone Transit Accessibility Peak within 60 Minutes for Basic Needs 1
  Disadvantage Zone Transit Accessibility Off Peak within 90 Minutes for Basic Needs 0
  Disadvantage Zone Transit Accessibility Off Peak within 90 Minutes for Basic Needs 1
  Disadvantage Zone Transit Accessibility Peak within 90 Minutes for Basic Needs 0
  Disadvantage Zone Transit Accessibility Peak within 90 Minutes for Basic Needs 1
  Average Commute Time by School Bus
  Nitrous oxide (NOx) emissions
  Volatile organic compounds (VOC) emissions
  Greenhouse gas emissions (CO2) equivalent
  Particulate matter 10 micrometers or smaller emissions (PM10)
  Particulate matter 2.5 micrometers or smaller emissions (PM2.5)
  Carbon monoxide (CO) emissions

In [14]:
# Read Experiments
experiments = pd.read_csv(r"EMAT/PAG/pag_emat_design_experiments_v2.csv")

In [15]:
experiments

,experiment,AV_Rates,EV_Rates,Ecommerce,HH_EMP_Distribution,HH_EMP_Growth,Heavy_Medium_Truck_Travel,Incentives_Special_AreaPop,Road_User_Fee,Roadway_Capacity_Improvement,Teleworking,Transit_Headways,Transit_Service_Expansion
0,1,0.426429,0.629416,0.064825,0.894206,0.070595,0.291441,0.074718,0.065340,High,0.260777,1.035500,No-Expansion
1,2,0.451099,0.557603,0.137546,0.172581,0.452954,0.588043,0.115119,0.000500,High and Medium,0.209456,0.856839,Expansion
2,3,0.403433,0.234635,0.038457,0.561412,0.940645,0.104067,0.466287,0.087974,High and Medium,0.149489,0.744309,No-Expansion
3,4,0.725207,0.098963,0.142539,0.997005,0.538545,0.565944,0.442189,0.030721,High and Medium,0.329631,1.337610,Expansion
4,5,0.871363,0.377913,0.079655,0.798971,0.478528,0.373775,0.251755,0.002257,High,0.363860,0.620246,Expansion
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,0.638118,0.636993,0.149330,0.008471,0.596505,0.004896,0.254383,0.012083,All,0.307486,1.513804,No-Expansion
116,117,0.448970,0.618047,0.083281,0.186780,0.348855,0.207100,0.015300,0.091326,High,0.196418,0.735662,No-Expansion
117,118,0.319670,0.733214,0.136239,0.956264,0.220410,0.166681,0.123819,0.061028,All,0.159654,0.994964,No-Expansion
118,119,0.695227,0.864764,0.083423,0.841143,0.144297,0.326049,0.181924,0.004358,All,0.112728,1.386445,No-Expansion
119,120,0.398615,0.173682,0.199256,0.851449,0.005164,0.757650,0.332646,0.005362,High,0.280422,0.764721,Expansion

In [16]:
results = pd.read_csv(os.path.join(model_results_dir, "final_merged_results.csv"))

In [17]:
results['experiment'] = results['RunID'].str.extract('(\d+)').astype(int)
results = results.drop(columns=['RunID'])

In [18]:
results.shape

(120, 255)

In [19]:
experiments_df = pd.merge(experiments, results, on='experiment', how='inner')
experiments_df

,experiment,AV_Rates,EV_Rates,Ecommerce,HH_EMP_Distribution,HH_EMP_Growth,Heavy_Medium_Truck_Travel,Incentives_Special_AreaPop,Road_User_Fee,Roadway_Capacity_Improvement,...,Disadvantage Zone Transit Accessibility Off Peak within 90 Minutes for Basic Needs 1,Disadvantage Zone Transit Accessibility Peak within 90 Minutes for Basic Needs 0,Disadvantage Zone Transit Accessibility Peak within 90 Minutes for Basic Needs 1,Average Commute Time by School Bus,Carbon monoxide (CO) emissions,Greenhouse gas emissions (CO2) equivalent,Nitrous oxide (NOx) emissions,Particulate matter 10 micrometers or smaller emissions (PM10),Particulate matter 2.5 micrometers or smaller emissions (PM2.5),Volatile organic compounds (VOC) emissions
0,1,0.426429,0.629416,0.064825,0.894206,0.070595,0.291441,0.074718,0.065340,High,...,NaN,NaN,NaN,NaN,6.816747e+09,1.984320e+12,613541010.0,292719433.5,57973022.47,8.856794e+08
1,2,0.451099,0.557603,0.137546,0.172581,0.452954,0.588043,0.115119,0.000500,High and Medium,...,2.070000,3.787692,0.996923,NaN,8.867268e+09,2.677424e+12,778998600.0,412355381.3,76374409.75,9.965334e+08
2,3,0.403433,0.234635,0.038457,0.561412,0.940645,0.104067,0.466287,0.087974,High and Medium,...,5.452857,5.530909,1.818182,NaN,8.786269e+09,2.568047e+12,712842510.0,351323111.8,69411143.69,1.031391e+09
3,4,0.725207,0.098963,0.142539,0.997005,0.538545,0.565944,0.442189,0.030721,High and Medium,...,4.564000,4.983684,1.631579,NaN,9.942429e+09,2.821317e+12,729401050.0,328746121.1,68751490.85,1.112212e+09
4,5,0.871363,0.377913,0.079655,0.798971,0.478528,0.373775,0.251755,0.002257,High,...,3.875000,3.588182,1.194545,NaN,8.279030e+09,2.373698e+12,671864850.0,305615061.0,62321938.59,9.738157e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,0.638118,0.636993,0.149330,0.008471,0.596505,0.004896,0.254383,0.012083,All,...,3.964286,4.110000,1.411250,NaN,7.670045e+09,2.259786e+12,678486030.0,323502545.4,63059759.86,9.198248e+08
116,117,0.448970,0.618047,0.083281,0.186780,0.348855,0.207100,0.015300,0.091326,High,...,2.722500,2.665000,1.010000,NaN,7.193162e+09,2.114924e+12,645270690.0,313137774.9,61166397.87,9.055693e+08
117,118,0.319670,0.733214,0.136239,0.956264,0.220410,0.166681,0.123819,0.061028,All,...,3.216000,4.255000,1.350000,NaN,6.905879e+09,2.050826e+12,640882200.0,314086965.5,60566120.59,8.806014e+08
118,119,0.695227,0.864764,0.083423,0.841143,0.144297,0.326049,0.181924,0.004358,All,...,3.378000,4.035000,1.485000,NaN,6.935131e+09,2.053526e+12,650572330.0,309498813.1,59564992.94,8.598993e+08
119,120,0.398615,0.173682,0.199256,0.851449,0.005164,0.757650,0.332646,0.005362,High,...,6.486667,6.243571,1.818571,NaN,8.354024e+09,2.370755e+12,651379720.0,294560333.9,61953908.95,1.027662e+09

In [20]:
cat_perf_measures = ['Roadway_Capacity_Improvement', 'Transit_Service_Expansion']

#convert to categrorical data type
for col in cat_perf_measures:
    experiments_df[col] = pd.Categorical(experiments_df[col], ordered=True)

In [21]:
# save results as parquet files and csv
#experiments_df.to_parquet("EMAT\\PAG\\Core Model.pq")
#experiments_df.to_csv("EMAT\\PAG\\Core Model.csv", index=False)

In [22]:
# FinalPriority
perf_df = pd.read_excel(
    os.path.join("crosswalks", "perf_measures_names.xlsx")
)

perf_df = perf_df.loc[perf_df['FinalPriority'].isin(['Y1', 'Y2'])]
perf_df = list(perf_df['PF Name in the Dashboard'])

measures_for_meta_models = perf_df

In [23]:
measures_for_meta_models

['Auto Mode Share',
 'Bike Mode Share',
 'Transit Mode Share',
 'Walk Mode Share',
 'Transit PMT',
 'Regional VMT',
 'Regional VMT per Capita',
 'Regional VHT',
 'Regional VHTper Capita',
 'Average Commute Time by Auto',
 'Average Commute Time by Transit',
 'Average Transit Travel Time',
 'Percentage of Population within Quarter Mile',
 'Percentage of Jobs within Quarter Mile',
 'AM Travel Time Index',
 'PM Travel Time Index',
 'Regional Speed',
 'Auto Accessibility Peak',
 'Auto Accessibility Peak within 30 Minutes',
 'Transit Accessibility Peak',
 'Transit Accessibility Off Peak within 45 Minutes',
 'Disadvantage Zone Auto Accessibility Peak for Jobs 0',
 'Disadvantage Zone Auto Accessibility Peak for Jobs 1',
 'Disadvantage Zone Transit Accessibility Peak within 45 Minutes for Jobs 0',
 'Disadvantage Zone Transit Accessibility Peak within 45 Minutes for Jobs 1',
 'Nitrous oxide (NOx) emissions',
 'Volatile organic compounds (VOC) emissions',
 'Greenhouse gas emissions (CO2) equivalent',
 'Particulate matter 10 micrometers or smaller emissions (PM10)',
 'Particulate matter 2.5 micrometers or smaller emissions (PM2.5)',
 'Carbon monoxide (CO) emissions']

In [24]:
%%time 

# Create MetaModels
mm = emat.create_metamodel(scope, experiments_df, suppress_converge_warnings=False, include_measures=measures_for_meta_models)

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:148: FutureWarning:

'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 3 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 5 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 6 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 0 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 13 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 3 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 6 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 10 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 11 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 0 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 1 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 8 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 8 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 7 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 9 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 2 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 2 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 8 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 1 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 3 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 9 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 0 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 13 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 14 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 9 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 6 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 8 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 3 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 6 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 9 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 0 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 10 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 1 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning:

The optimal value found for dimension 10 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning:

The optimal value found for dimension 11 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.

CPU times: user 7min 27s, sys: 1.48 s, total: 7min 28s
Wall time: 29.1 s

In [25]:
# extract R2 values from Linear Regression
mm.function.regression.estimators_[0].r2

Auto Mode Share                                                              0.973897
Bike Mode Share                                                              0.962534
Transit Mode Share                                                           0.963846
Walk Mode Share                                                              0.902791
Transit PMT                                                                  0.917603
Regional VMT                                                                 0.669360
Regional VMT per Capita                                                      0.565693
Regional VHT                                                                 0.703464
Regional VHTper Capita                                                       0.514490
Average Commute Time by Auto                                                 0.743420
Average Commute Time by Transit                                              0.842200
Average Transit Travel Time                                                  0.884549
Percentage of Population within Quarter Mile                                 0.707626
Percentage of Jobs within Quarter Mile                                       0.896750
AM Travel Time Index                                                         0.876879
PM Travel Time Index                                                         0.827045
Regional Speed                                                               0.872867
Auto Accessibility Peak                                                      0.826148
Auto Accessibility Peak within 30 Minutes                                    0.854803
Transit Accessibility Peak                                                   0.898297
Transit Accessibility Off Peak within 45 Minutes                             0.922375
Disadvantage Zone Auto Accessibility Peak for Jobs 0                         0.847075
Disadvantage Zone Auto Accessibility Peak for Jobs 1                         0.857123
Disadvantage Zone Transit Accessibility Peak within 45 Minutes for Jobs 0    0.961067
Disadvantage Zone Transit Accessibility Peak within 45 Minutes for Jobs 1    0.944066
Nitrous oxide (NOx) emissions                                                0.665772
Volatile organic compounds (VOC) emissions                                   0.920211
Greenhouse gas emissions (CO2) equivalent                                    0.817802
Particulate matter 2.5 micrometers or smaller emissions (PM2.5)              0.697291
Carbon monoxide (CO) emissions                                               0.878299
dtype: float64

In [26]:
# Extract Coeff from Linear Regression
mm.function.regression.estimators_[0].coef_

array([[ 3.88345506e-04,  2.67282784e-04, -2.02978904e-02,
         6.20994300e-03, -7.25839776e-03,  8.71645862e-05,
        -4.14489614e-03,  5.86541162e-03, -3.53412319e-02,
        -3.10894158e-03, -8.23557798e-04,  8.23557798e-04,
        -1.00434899e-03,  6.24050011e-04,  3.80298976e-04],
       [-1.19448152e-03,  1.55481265e-04,  4.68761990e-03,
        -9.08267505e-04,  1.60007474e-04, -1.33583859e-04,
        -7.96835332e-04,  1.11813460e-04,  6.33963391e-03,
        -3.34821422e-04,  4.55670606e-06, -4.55670606e-06,
        -4.62607113e-05,  7.09432574e-06,  3.91663856e-05],
       [-1.16040064e-03,  1.01488292e-03,  1.25428226e-02,
        -8.40019516e-04, -2.43560308e-03, -3.00165144e-04,
         1.08828814e-03, -6.09681351e-03,  2.71130205e-03,
         9.85036814e-04,  9.11588368e-04, -9.11588368e-04,
         9.43666050e-04, -3.82650367e-04, -5.61015684e-04],
       [ 1.62903864e-03, -1.51709483e-03,  5.15289433e-03,
        -3.19385380e-03,  1.07617507e-02,  3.33066908e-04,
         3.30493767e-03,  5.98733349e-05,  1.85700671e-02,
        -7.28971985e-04, -1.13650917e-04,  1.13650917e-04,
         1.27919426e-04, -1.78426896e-04,  5.05074707e-05],
       [ 1.49505576e+04,  7.07057567e+03,  1.24562105e+05,
        -9.85313976e+03, -2.66155303e+04, -3.98066206e+03,
         2.43333944e+04, -6.94361619e+04, -2.71262330e+04,
         1.47779124e+04,  1.07310126e+04, -1.07310126e+04,
         1.23846014e+04, -5.21884492e+03, -7.16575650e+03],
       [ 4.80595135e+06,  1.41618557e+05,  8.63246289e+05,
         1.08965538e+06, -4.89346619e+06,  2.16561427e+06,
         1.23405834e+07, -1.82342956e+05, -8.22905977e+06,
         4.91352437e+05, -6.85562622e+04,  6.85562622e+04,
         2.25753384e+05, -2.00251152e+05, -2.55022322e+04],
       [-1.88159620e+00, -1.22892066e-01,  7.27608723e-01,
         1.07239425e+00, -4.03558294e+00,  1.64217499e+00,
         9.74710844e+00, -3.08148813e-01, -5.52983647e+00,
         3.69714121e-01,  3.88431766e-02, -3.88431766e-02,
         1.63343657e-01, -2.25567207e-01,  6.22235498e-02],
       [ 1.62196142e+05,  1.42037436e+04, -1.09683072e+05,
         3.52944665e+04, -1.90461392e+05,  4.66388307e+04,
         3.15593777e+05, -8.25148127e+03, -2.83305719e+05,
         1.59242876e+04, -7.86097952e+02,  7.86097952e+02,
         7.03133590e+02,  2.74825604e+03, -3.45138963e+03],
       [-1.05651786e-02,  4.56865148e-03, -8.40709204e-02,
         3.24537852e-02, -1.49492689e-01,  3.56851103e-02,
         2.48985973e-01, -1.02929547e-02, -1.92659071e-01,
         1.09982276e-02,  1.86598749e-03, -1.86598749e-03,
         1.13671355e-04,  3.92955493e-04, -5.06626849e-04],
       [ 1.17938898e+00, -2.67928496e-01, -3.17521092e+00,
         8.79146285e-01, -3.45181545e+00, -9.38933211e-04,
         2.86518699e+00,  3.47094521e-02, -6.84407446e+00,
        -1.19251106e-01, -1.57219955e-02,  1.57219955e-02,
        -7.86576677e-02,  1.40843553e-01, -6.21858851e-02],
       [ 3.63194625e-01,  5.92237973e-01, -8.09529362e+00,
         3.92889283e-01, -3.06596496e+00, -7.40613903e-01,
         6.84138661e+00,  4.21192203e+00, -1.66853798e+01,
        -7.86912607e-01,  1.34881030e+00, -1.34881030e+00,
         1.77540495e+00, -1.21191439e+00, -5.63490560e-01],
       [-6.28136946e-01, -3.83285112e-01, -4.52188110e+00,
        -2.15632776e-01, -3.67448351e+00, -5.29673579e-01,
         3.73534943e+00,  6.06950947e+00, -8.11167767e+00,
        -2.32751249e-01,  1.19959135e+00, -1.19959135e+00,
         1.30077665e+00, -8.36040750e-01, -4.64735898e-01],
       [-1.43332567e-02,  2.63121052e-02, -1.66031184e-04,
        -1.93548110e-05, -2.16717774e-03,  1.58530343e-03,
        -7.82439921e-03, -1.20819514e-03, -2.92166311e-02,
        -2.68927706e-04,  8.23377798e-04, -8.23377798e-04,
        -7.95261984e-04, -4.54077648e-05,  8.40669749e-04],
       [-3.94797789e-02,  4.45121448e-02,  2.42231858e-04,
         3.87870132e-03, -4.59321909e-03, -1.32442719e-03,
        -1.95871671e-02, -2.66096076e-03, -3.11064649e-03,
         1.24180411e-03,  1.11448693e-03, -1.11448693e-03,
        -4.61731492e-04, -7.27020610e-04,  1.18875210e-03],
       [ 1.07443867e-01,  7.70430888e-03, -2.42535205e-01,
         3.44186236e-02, -1.35379612e-01,  1.79798358e-02,
         1.54151316e-01, -7.68615470e-03, -2.39694407e-01,
         1.66378926e-03,  5.79366263e-04, -5.79366263e-04,
        -7.13385708e-03,  1.33797360e-02, -6.24587891e-03],
       [ 2.13735118e-01,  2.29907494e-02, -3.85437770e-01,
         6.50690181e-02, -4.05364502e-01,  2.77007414e-02,
         2.20192033e-01, -2.13928168e-02, -4.64865179e-01,
         5.99053033e-03,  3.16179090e-03, -3.16179090e-03,
        -1.42045308e-02,  2.50375134e-02, -1.08329825e-02],
       [-2.76633479e+00, -7.87260537e-01,  8.40616730e+00,
        -5.43006109e-01,  3.98302155e+00,  3.38065883e-01,
        -3.89455693e-01,  3.89776115e-01,  3.51173785e+00,
        -5.82741963e-01, -6.25321219e-02,  6.25321219e-02,
         2.32432430e-01, -4.32703803e-01,  2.00271373e-01],
       [-2.80893088e+03,  3.88627478e+03,  2.06616439e+04,
        -3.43715348e+03,  1.57071384e+04, -1.26201555e+03,
        -1.43130566e+04,  1.35323276e+03,  7.37086895e+03,
        -1.14783874e+03, -1.94543139e+02,  1.94543139e+02,
         2.95898619e+02, -6.89727222e+02,  3.93828604e+02],
       [-1.48901838e+04,  1.89834534e+04,  1.14829421e+05,
        -1.79802765e+04,  8.61623138e+04, -6.31474820e+03,
        -7.90282286e+04,  6.75184659e+03,  3.47873874e+04,
        -4.54132585e+03, -1.21418590e+03,  1.21418590e+03,
         2.72110631e+03, -4.72641154e+03,  2.00530523e+03],
       [-1.53946780e+01,  2.23137655e+02,  3.28219807e+02,
        -1.15752112e+02,  4.76253838e+02, -7.41828255e+01,
        -3.72719879e+02, -1.40123350e+03,  4.41257559e+02,
        -1.18669297e+01,  1.20699033e+01, -1.20699033e+01,
        -8.12740295e+00,  2.91071808e+01, -2.09797779e+01],
       [ 7.25736732e+02,  7.05993632e+03,  9.17002393e+02,
        -1.34011553e+03,  2.95654843e+03, -1.24190042e+03,
        -4.10445173e+03, -3.67518673e+04,  1.17534982e+04,
         1.11399351e+03,  6.18154443e+02, -6.18154443e+02,
         1.54059595e+02,  5.40678064e+02, -6.94737659e+02],
       [ 5.22508605e+04,  1.79208729e+04,  3.55807544e+04,
        -6.81313177e+03,  8.49807076e+03, -2.33709857e+03,
        -6.31703624e+04,  3.62622679e+03, -1.27200263e+04,
        -1.02175970e+03, -1.47923139e+03,  1.47923139e+03,
         1.98157346e+03, -1.28181892e+03, -6.99754538e+02],
       [-1.76724884e+04,  1.72426576e+04,  1.13332236e+05,
        -1.69443440e+04,  8.09207112e+04, -6.42647791e+03,
        -7.17938826e+04,  6.24627598e+03,  2.74303813e+04,
        -4.78255902e+03, -1.09710637e+03,  1.09710637e+03,
         2.84337643e+03, -5.23739394e+03,  2.39401751e+03],
       [ 8.04379347e+03,  2.11645258e+04,  2.79738703e+03,
        -2.24236050e+03,  5.56269422e+03, -5.55242163e+02,
        -1.17374884e+04, -8.18207601e+04,  1.77196757e+04,
        -3.61703527e+02,  1.15762566e+03, -1.15762566e+03,
         1.07499256e+03,  4.93023199e+02, -1.56801576e+03],
       [-2.72538425e+03,  6.95421503e+03,  7.08049927e+03,
        -2.12115235e+03,  8.95256751e+03, -8.68467727e+02,
        -9.24484678e+03, -2.21871383e+04,  5.64971698e+03,
        -2.18551179e+02,  2.44544378e+02, -2.44544378e+02,
         2.24469094e+01,  2.16109599e+02, -2.38556509e+02],
       [ 1.02635078e+08,  5.20950377e+06, -4.41130744e+06,
        -5.58127649e+07, -1.11306442e+08,  3.87338916e+07,
         2.34349919e+08, -4.77601916e+06, -1.94832163e+08,
         1.16763550e+07, -1.12136820e+06,  1.12136820e+06,
         3.02548908e+06, -9.68412700e+05, -2.05707638e+06],
       [ 5.13543053e+07,  4.66608599e+06, -3.36564389e+06,
        -2.94540247e+08, -6.83549987e+07,  1.92301243e+07,
         1.58829026e+08, -4.37975182e+06, -2.31850428e+08,
         1.53731447e+07, -2.21460344e+06,  2.21460344e+06,
         1.99546284e+06,  2.17835814e+06, -4.17382098e+06],
       [ 4.08462979e+11,  2.49701298e+10,  6.75326786e+10,
        -7.63326490e+11, -4.36781746e+11,  1.71478310e+11,
         1.03768289e+12, -2.31698157e+10, -9.59421588e+11,
         5.17814860e+10, -7.12400740e+09,  7.12400740e+09,
         2.38019867e+10, -9.97925207e+09, -1.38227346e+10],
       [ 1.16042892e+07,  1.08838183e+06, -5.92533686e+06,
        -6.88029046e+06, -1.26625084e+07,  3.46685418e+06,
         2.27886492e+07, -6.52813582e+05, -2.21198112e+07,
         1.34709717e+06, -5.97121980e+04,  5.97121980e+04,
         3.17219510e+04,  3.80818066e+05, -4.12540017e+05],
       [ 1.13363036e+09,  1.02283018e+08,  5.85933527e+08,
        -3.16078174e+09, -1.24419038e+09,  4.82572655e+08,
         3.17301258e+09, -7.81148825e+07, -3.23056197e+09,
         1.53715672e+08, -2.79078663e+07,  2.79078663e+07,
         7.96589790e+07, -4.03518283e+07, -3.93071506e+07]])

In [27]:
# Extract Intercepts from Linear Regression
mm.function.regression.estimators_[0].intercept_

array([8.40312491e-01, 1.52502809e-02, 1.68117079e-02, 1.11764633e-01,
       1.52722871e+05, 2.28439038e+07, 2.09170312e+01, 6.20152780e+05,
       5.57100161e-01, 2.26992291e+01, 6.27546261e+01, 4.47963195e+01,
       3.94912833e-01, 6.30307429e-01, 1.46380206e+00, 1.84661834e+00,
       3.72977859e+01, 3.68056531e+04, 1.82267250e+05, 3.24577229e+03,
       7.62896349e+04, 3.58487982e+05, 1.50555854e+05, 1.97589109e+05,
       5.69126527e+04, 6.53904004e+08, 1.09022867e+09, 2.45580281e+12,
       6.51518891e+07, 8.63885689e+09])

In [28]:
# Extract p values from Linear Regression
mm.function.regression.estimators_[0].p_

array([[3.53956901e-01, 5.16881484e-01, 0.00000000e+00, 0.00000000e+00,
        3.48212785e-07, 8.32926718e-01, 4.84966397e-02, 0.00000000e+00,
        1.48769885e-13, 2.76527277e-04,            nan,            nan,
                   nan,            nan,            nan],
       [0.00000000e+00, 1.21450743e-01, 0.00000000e+00, 2.90878432e-14,
        6.21598552e-01, 1.83930631e-01, 1.16240532e-01, 9.44170509e-02,
        7.69808439e-09, 9.73680051e-02,            nan,            nan,
                   nan,            nan,            nan],
       [1.12814215e-03, 3.66429297e-03, 0.00000000e+00, 1.93542060e-02,
        3.01599235e-02, 3.82717093e-01, 5.29482426e-01, 0.00000000e+00,
        4.35027953e-01, 1.54192352e-01,            nan,            nan,
                   nan,            nan,            nan],
       [1.12752030e-09, 6.41331632e-09, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.69363620e-01, 7.51981971e-03, 7.08414329e-01,
        1.08966169e-11, 1.33775415e-01,            nan,            nan,
                   nan,            nan,            nan],
       [8.72030846e-03, 2.02341390e-01, 0.00000000e+00, 8.72897568e-02,
        1.39776711e-01, 4.73015015e-01, 3.84159963e-01, 0.00000000e+00,
        6.28189405e-01, 1.85107523e-01,            nan,            nan,
                   nan,            nan,            nan],
       [0.00000000e+00, 7.66240302e-01, 7.12930120e-02, 2.89825021e-02,
        1.97786468e-03, 1.47647532e-05, 1.27269200e-06, 5.65250698e-01,
        9.03781088e-02, 6.08000102e-01,            nan,            nan,
                   nan,            nan,            nan],
       [1.15279122e-06, 7.32797789e-01, 4.46262788e-02, 4.76663632e-03,
        7.73273622e-04, 1.38450870e-05, 4.67308802e-07, 1.99802451e-01,
        1.31512175e-01, 6.09499234e-01,            nan,            nan,
                   nan,            nan,            nan],
       [0.00000000e+00, 3.59077243e-01, 1.30398137e-10, 2.92887239e-02,
        2.38101918e-04, 3.21375668e-03, 9.78661715e-05, 4.22983812e-01,
        7.26728287e-02, 6.08490667e-01,            nan,            nan,
                   nan,            nan,            nan],
       [3.73935340e-01, 6.95942770e-01, 8.05713274e-11, 8.37272107e-03,
        1.41435257e-04, 2.87925256e-03, 5.06237445e-05, 1.87348685e-01,
        1.05940487e-01, 6.39819010e-01,            nan,            nan,
                   nan,            nan,            nan],
       [1.41454969e-06, 2.40838015e-01, 0.00000000e+00, 3.03701465e-04,
        8.52587388e-06, 9.96719195e-01, 1.40880344e-02, 8.18772949e-01,
        3.65353088e-03, 7.94463604e-01,            nan,            nan,
                   nan,            nan,            nan],
       [5.27666300e-01, 2.96726477e-01, 0.00000000e+00, 5.03284676e-01,
        9.73711390e-02, 1.93857939e-01, 1.82590725e-02, 0.00000000e+00,
        4.34102108e-03, 4.89716456e-01,            nan,            nan,
                   nan,            nan,            nan],
       [1.73826341e-01, 3.98375411e-01, 0.00000000e+00, 6.46058058e-01,
        1.37941290e-02, 2.45270032e-01, 1.04887870e-01, 0.00000000e+00,
        7.94679066e-02, 7.98317560e-01,            nan,            nan,
                   nan,            nan,            nan],
       [3.92622823e-10, 0.00000000e+00, 9.35253096e-01, 9.92725861e-01,
        7.44653354e-01, 4.41211033e-01, 4.50486799e-01, 3.76453858e-01,
        1.61475343e-01, 9.47954643e-01,            nan,            nan,
                   nan,            nan,            nan],
       [0.00000000e+00, 0.00000000e+00, 9.08820345e-01, 7.96837588e-02,
        5.05090884e-01, 5.33913678e-01, 6.97512745e-02, 6.14720450e-02,
        8.84934292e-01, 7.70894255e-01,            nan,            nan,
                   nan,            nan,            nan],
       [0.00000000e+00, 4.73798217e-01, 0.00000000e+00, 2.47985714e-03,
        1.74850255e-04, 9.73326106e-02, 5.30804750e-03, 2.83467942e-01,
        2.94818569e-02, 9.38583949e-01,            nan,            nan,
                   nan,            nan,            nan],
       [1.11022302e-15, 3.05019863e-01, 0.00000000e+00, 5.80205025e-03,
        1.73522527e-07, 2.18357073e-01, 5.33607459e-02, 1.52357566e-01,
        4.21961040e-02, 8.93964340e-01,            nan,            nan,
                   nan,            nan,            nan],
       [1.36828326e-11, 3.05763200e-02, 0.00000000e+00, 1.47347549e-01,
        9.01604546e-04, 3.50077897e-01, 8.30457298e-01, 1.05790220e-01,
        3.36782255e-01, 4.21348522e-01,            nan,            nan,
                   nan,            nan,            nan],
       [8.98101952e-03, 3.01937966e-04, 0.00000000e+00, 1.86461796e-03,
        9.50580846e-06, 2.28828038e-01, 7.53113447e-03, 5.30403837e-02,
        4.85680117e-01, 5.83974630e-01,            nan,            nan,
                   nan,            nan,            nan],
       [5.42087325e-03, 3.77232199e-04, 0.00000000e+00, 1.08766929e-03,
        1.28720227e-06, 2.25674446e-01, 3.10045823e-03, 5.21177271e-02,
        5.07848423e-01, 6.62793320e-01,            nan,            nan,
                   nan,            nan,            nan],
       [8.43820257e-01, 4.47542779e-03, 4.05341242e-05, 1.48657861e-01,
        5.88019867e-02, 3.37731964e-01, 3.38994765e-01, 0.00000000e+00,
        5.71964906e-01, 9.38877451e-01,            nan,            nan,
                   nan,            nan,            nan],
       [6.70753334e-01, 5.42598056e-05, 5.84690270e-01, 4.42256265e-01,
        5.88244350e-01, 4.62020221e-01, 6.29160074e-01, 0.00000000e+00,
        4.90799623e-01, 7.41762350e-01,            nan,            nan,
                   nan,            nan,            nan],
       [0.00000000e+00, 1.44009515e-09, 0.00000000e+00, 1.65345107e-02,
        3.34443992e-01, 3.90088388e-01, 1.04848261e-05, 4.60669253e-02,
        6.42985888e-01, 8.51043163e-01,            nan,            nan,
                   nan,            nan,            nan],
       [8.38950378e-04, 9.37706876e-04, 0.00000000e+00, 1.65021339e-03,
        3.17259235e-06, 2.08511608e-01, 5.97348397e-03, 6.65137551e-02,
        5.94081370e-01, 6.39426714e-01,            nan,            nan,
                   nan,            nan,            nan],
       [2.99679382e-03, 9.79438752e-13, 2.84559869e-01, 4.08399104e-01,
        5.12536241e-01, 8.32304939e-01, 3.75084631e-01, 0.00000000e+00,
        5.04042877e-01, 9.45126156e-01,            nan,            nan,
                   nan,            nan,            nan],
       [4.01460716e-03, 1.18693944e-11, 5.32329736e-12, 2.69706509e-02,
        3.15762484e-03, 3.44973817e-01, 4.75761456e-02, 0.00000000e+00,
        5.42670944e-01, 9.05415716e-01,            nan,            nan,
                   nan,            nan,            nan],
       [0.00000000e+00, 6.07964932e-01, 6.63060074e-01, 5.85927624e-07,
        9.95316462e-04, 2.30716307e-04, 1.27675944e-05, 4.79857309e-01,
        6.03201803e-02, 5.67387380e-01,            nan,            nan,
                   nan,            nan,            nan],
       [1.76205070e-07, 6.06923757e-01, 7.09704742e-01, 0.00000000e+00,
        2.17725691e-02, 3.63204816e-02, 7.39672909e-04, 4.68192692e-01,
        1.28835592e-02, 3.99600564e-01,            nan,            nan,
                   nan,            nan,            nan],
       [3.55271368e-15, 5.68709233e-01, 1.23975781e-01, 0.00000000e+00,
        2.63145931e-03, 1.60929957e-04, 7.83617874e-06, 4.26972890e-01,
        3.24273732e-02, 5.56558241e-01,            nan,            nan,
                   nan,            nan,            nan],
       [0.00000000e+00, 3.45197202e-01, 1.09228468e-06, 7.49604641e-08,
        9.57385068e-04, 3.25591960e-03, 1.52604898e-04, 3.94546503e-01,
        5.99519580e-02, 5.60572922e-01,            nan,            nan,
                   nan,            nan,            nan],
       [8.41549053e-14, 4.32908872e-01, 1.61192342e-05, 0.00000000e+00,
        3.91362898e-03, 3.41039556e-04, 4.59484736e-06, 3.68195485e-01,
        1.57850103e-02, 5.57407831e-01,            nan,            nan,
                   nan,            nan,            nan]])

In [29]:
# Extract t values from Linear Regression
mm.function.regression.estimators_[0].t_

array([[ 9.31062753e-01,  6.50358036e-01, -4.95295286e+01,
         1.45876719e+01, -5.44139519e+00,  2.11474794e-01,
        -1.99623967e+00,  2.14529244e+01, -8.48588030e+00,
        -3.76332199e+00,             nan,             nan,
                    nan,             nan,             nan],
       [-1.18189854e+01,  1.56134790e+00,  4.72069318e+01,
        -8.80546391e+00,  4.95050915e-01, -1.33755798e+00,
        -1.58382687e+00,  1.68780469e+00,  6.28231184e+00,
        -1.67267724e+00,             nan,             nan,
                    nan,             nan,             nan],
       [-3.34873120e+00,  2.97241284e+00,  3.68400518e+01,
        -2.37519576e+00, -2.19779752e+00, -8.76577783e-01,
         6.30891371e-01, -2.68412402e+01,  7.83618680e-01,
         1.43523475e+00,             nan,             nan,
                    nan,             nan,             nan],
       [ 6.68814700e+00, -6.32132339e+00,  2.15316981e+01,
        -1.28477524e+01,  1.38154866e+01,  1.38376958e+00,
         2.72568746e+00,  3.75003403e-01,  7.63558726e+00,
        -1.51106591e+00,             nan,             nan,
                    nan,             nan,             nan],
       [ 2.67291158e+00,  1.28292962e+00,  2.26655239e+01,
        -1.72599506e+00, -1.48789115e+00, -7.20178881e-01,
         8.73913120e-01, -1.89382675e+01, -4.85703507e-01,
         1.33394658e+00,             nan,             nan,
                    nan,             nan,             nan],
       [ 9.96675177e+00,  2.98067959e-01,  1.82205555e+00,
         2.21411993e+00, -3.17321646e+00,  4.54478398e+00,
         5.14100852e+00, -5.76886798e-01, -1.70914550e+00,
         5.14476490e-01,             nan,             nan,
                    nan,             nan,             nan],
       [-5.16426117e+00, -3.42315426e-01,  2.03250812e+00,
         2.88385850e+00, -3.46335398e+00,  4.56098949e+00,
         5.37397853e+00, -1.29023734e+00, -1.52001756e+00,
         5.12325480e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.03646128e+01,  9.21162485e-01, -7.13353491e+00,
         2.20981994e+00, -3.80564570e+00,  3.01590798e+00,
         4.05115963e+00, -8.04399551e-01, -1.81310291e+00,
         5.13772346e-01,             nan,             nan,
                    nan,             nan,             nan],
       [-8.92932370e-01,  3.91877754e-01, -7.23169579e+00,
         2.68747717e+00, -3.95066780e+00,  3.05201481e+00,
         4.22722112e+00, -1.32711673e+00, -1.63074379e+00,
         4.69312990e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 5.11611241e+00, -1.17956744e+00, -1.40187152e+01,
         3.73664517e+00, -4.68208631e+00, -4.12169245e-03,
         2.49674588e+00,  2.29698473e-01, -2.97339281e+00,
        -2.61182200e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 6.33682069e-01,  1.04869479e+00, -1.43753105e+01,
         6.71645160e-01, -1.67266137e+00, -1.30762054e+00,
         2.39780852e+00,  1.12108790e+01, -2.91556447e+00,
        -6.93196971e-01,             nan,             nan,
                    nan,             nan,             nan],
       [-1.36930295e+00, -8.47984688e-01, -1.00326801e+01,
        -4.60572158e-01, -2.50466900e+00, -1.16845337e+00,
         1.63574198e+00,  2.01848783e+01, -1.77096687e+00,
        -2.56174190e-01,             nan,             nan,
                    nan,             nan,             nan],
       [-6.90716583e+00,  1.28686046e+01, -8.14324110e-02,
        -9.13864151e-03, -3.26556528e-01,  7.73081490e-01,
        -7.57433250e-01, -8.88217707e-01, -1.41006681e+00,
        -6.54317748e-02,             nan,             nan,
                    nan,             nan,             nan],
       [-1.83842074e+01,  2.10363107e+01,  1.14803224e-01,
         1.76967795e+00, -6.68799894e-01, -6.24102835e-01,
        -1.83223083e+00, -1.89032295e+00, -1.45069263e-01,
         2.91958713e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 9.87863002e+00,  7.18901898e-01, -2.26956434e+01,
         3.10060390e+00, -3.89203903e+00,  1.67285646e+00,
         2.84708665e+00, -1.07808138e+00, -2.20712808e+00,
         7.72345378e-02,             nan,             nan,
                    nan,             nan,             nan],
       [ 9.44194022e+00,  1.03076424e+00, -1.73297482e+01,
         2.81641933e+00, -5.59937959e+00,  1.23832495e+00,
         1.95400343e+00, -1.44171916e+00, -2.05668095e+00,
         1.33613020e-01,             nan,             nan,
                    nan,             nan,             nan],
       [-7.58992072e+00, -2.19215793e+00,  2.34737866e+01,
        -1.45973802e+00,  3.41707091e+00,  9.38624129e-01,
        -2.14649024e-01,  1.63145486e+00,  9.64959612e-01,
        -8.07247932e-01,             nan,             nan,
                    nan,             nan,             nan],
       [-2.66232802e+00,  3.73830619e+00,  1.99314091e+01,
        -3.19195777e+00,  4.65507213e+00, -1.21043949e+00,
        -2.72515531e+00,  1.95668245e+00,  6.99670797e-01,
        -5.49287274e-01,             nan,             nan,
                    nan,             nan,             nan],
       [-2.83985900e+00,  3.67445384e+00,  2.22896123e+01,
        -3.35993432e+00,  5.13834082e+00, -1.21873877e+00,
        -3.02773128e+00,  1.96447553e+00,  6.64466487e-01,
        -4.37298042e-01,             nan,             nan,
                    nan,             nan,             nan],
       [-1.97497249e-01,  2.90525436e+00,  4.28556266e+00,
        -1.45498015e+00,  1.91045919e+00, -9.63056311e-01,
        -9.60530939e-01, -2.74238416e+01,  5.66940063e-01,
        -7.68647042e-02,             nan,             nan,
                    nan,             nan,             nan],
       [ 4.26311849e-01,  4.20891290e+00,  5.48240847e-01,
        -7.71308721e-01,  5.43052891e-01, -7.38232125e-01,
        -4.84330491e-01, -3.29348011e+01,  6.91464664e-01,
         3.30391684e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.90670740e+01,  6.63698173e+00,  1.32147326e+01,
        -2.43598773e+00,  9.69660676e-01, -8.63029228e-01,
        -4.63065403e+00,  2.01870522e+00, -4.64871760e-01,
        -1.88251100e-01,             nan,             nan,
                    nan,             nan,             nan],
       [-3.43883390e+00,  3.40516808e+00,  2.24449982e+01,
        -3.23054621e+00,  4.92359158e+00, -1.26544823e+00,
        -2.80633360e+00,  1.85422316e+00,  5.34564221e-01,
        -4.69863794e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 3.03890462e+00,  8.11494455e+00,  1.07562612e+00,
        -8.30040523e-01,  6.57128315e-01, -2.12273835e-01,
        -8.90778437e-01, -4.71570909e+01,  6.70450124e-01,
        -6.89933210e-02,             nan,             nan,
                    nan,             nan,             nan],
       [-2.94188055e+00,  7.61844372e+00,  7.77882133e+00,
        -2.24340073e+00,  3.02171661e+00, -9.48656191e-01,
        -2.00463528e+00, -3.65364140e+01,  6.10771176e-01,
        -1.19110101e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 9.98818917e+00,  5.14526981e-01, -4.36929019e-01,
        -5.32184449e+00, -3.38703805e+00,  3.81452040e+00,
         4.58135672e+00, -7.09062208e-01, -1.89891769e+00,
         5.73715231e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 5.59592358e+00,  5.16022347e-01, -3.73263652e-01,
        -3.14468584e+01, -2.32902436e+00,  2.12048340e+00,
         3.47666742e+00, -7.28067686e-01, -2.53021465e+00,
         8.45776823e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 9.21556182e+00,  5.71756055e-01,  1.55072831e+00,
        -1.68739653e+01, -3.08135993e+00,  3.91503979e+00,
         4.70296918e+00, -7.97478591e-01, -2.16786958e+00,
         5.89850258e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 9.96146668e+00,  9.48215131e-01, -5.17690757e+00,
        -5.78694319e+00, -3.39886038e+00,  3.01160624e+00,
         3.92972071e+00, -8.54911704e-01, -1.90169431e+00,
         5.83850714e-01,             nan,             nan,
                    nan,             nan,             nan],
       [ 8.59725540e+00,  7.87250142e-01,  4.52261199e+00,
        -2.34866226e+01, -2.95042129e+00,  3.70347090e+00,
         4.83390947e+00, -9.03752433e-01, -2.45369729e+00,
         5.88578854e-01,             nan,             nan,
                    nan,             nan,             nan]])

In [31]:
design = mm.design_experiments(n_samples=10000, sampler='lhs')
mm_result = mm.run_experiments(design)
mm_result = mm_result.reset_index().rename(columns={'index':'experiment'}).set_index('experiment')


from emat.analysis import Visualizer
viz = Visualizer(scope=scope, data=mm_result)

In [32]:
with timing_log("crossvalidate metamodel"):
    display(mm.cross_val_scores())

<TIME BEGINS> crossvalidate metamodel
/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:148: FutureWarning:

'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:148: FutureWarning:

'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:148: FutureWarning:

'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:148: FutureWarning:

'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py:148: FutureWarning:

'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 1 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 1 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 3 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 12 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 13 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 1 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 8 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning:

The optimal value found for dimension 14 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 2 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 5 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 6 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning:

The optimal value found for dimension 11 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 6 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning:

The optimal value found for dimension 12 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 6 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 8 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 10 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 1 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 3 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 13 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 6 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 3 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 6 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 7 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 10 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning:

The optimal value found for dimension 14 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 9 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 2 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 7 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 10 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 12 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 14 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 1 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 7 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 10 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning:

The optimal value found for dimension 11 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 2 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 9 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:420: ConvergenceWarning:

The optimal value found for dimension 11 of parameter length_scale is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 0 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 4 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 5 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 12 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 0 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 5 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 12 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 5 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:

The optimal value found for dimension 9 of parameter length_scale is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/gaussian_process/kernels.py:430: ConvergenceWarning:


< TIME ENDS > crossvalidate metamodel <21.77s>

In [33]:
feature_scores(scope, mm_result, cmap='copper', random_state=1)

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/sklearn/ensemble/_forest.py:400: FutureWarning:

Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.

In [34]:
viz = Visualizer(scope=scope, data=mm_result)

In [35]:
display(viz.complete())

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Auto Trips not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Bike Trips not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional School Bus Trips not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Taxi Trips not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Transit Trips not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Walk Trips not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

School Bus Mode Share not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Taxi Mode Share not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Auto PMT not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Bike PMT not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

SchoolBus PMT not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Taxi PMT not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Walk PMT not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Auto PMT Ratio not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Bike PMT Ratio not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

School Bus PMT Ratio not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Taxi PMT Ratio not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit PMT Ratio not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Walk PMT Ratio not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Congested VMT not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Congested VMT PCT not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Average Commute Time by Bike not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Average Commute Time by Taxi not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Average Commute Time by Walk not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Highway Lane Miles of Freeways not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Highway Lane Miles of Parkways not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Highway Lane Miles of Major Arterial not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Highway Lane Miles of Minor Arterial not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Highway Lane Miles of Collector not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Highway Lane Miles of Ramps not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Highway Lane Miles of Frontage Road not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Rural Transit Miles Per Frequency - PK not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regular Transit Miles Per Frequency - PK not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Express Transit Miles Per Frequency - PK not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

CatTran Transit Miles Per Frequency - PK not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional BRT Transit Miles Per Frequency - PK not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Rural Transit Miles Per Frequency - OP not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regular Transit Miles Per Frequency - OP not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Express Transit Miles Per Frequency - OP not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

CatTran Transit Miles Per Frequency - OP not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional BRT Transit Miles Per Frequency - OP not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Total Population not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Total Population within Quarter Mile not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Total DISADV Population not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

DISADV Population within QuarterMile not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Percentage of DISADV Population within Quarter Mile not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Total Jobs not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Total Jobs within Quarter Mile not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Regional Total DISADV Jobs not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

DISADV Jobs within QuarterMile not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Percentage of DISADV Jobs within Quarter Mile not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

PK Average Transit Speed not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

OP Average Transit Speed not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

DY Average Transit Speed not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Auto Accessibility Off Peak not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Auto Accessibility Off Peak within 30 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Auto Accessibility Percentage Off Peak within 30 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Auto Accessibility Percentage Peak within 30 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Off Peak not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Off Peak within 60 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Off Peak within 90 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Percentage Off Peak within 45 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Percentage Off Peak within 60 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Percentage Off Peak within 90 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Peak within 45 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Peak within 60 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Peak within 90 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Percetange Peak within 45 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Percentage Peak within 60 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Transit Accessibility Percentage Peak within 90 Minutes not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Auto 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Auto 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Bike 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Bike 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Taxi 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Taxi 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Transit 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Transit 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Walk 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Home to Work Commute Time by Walk 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Auto 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Auto 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Bike 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Bike 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Taxi 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Taxi 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Transit 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Transit 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Walk 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Work to Home Commute Time by Walk 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Auto 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Bike 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by SchoolBus 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Taxi 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Transit 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Walk 0 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Auto 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Bike 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by SchoolBus 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Taxi 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Transit 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Household by Walk 1 not in data

/Users/wsp/Downloads/pag_runs_processing/.venv/lib/python3.9/site-packages/emat/analysis/explore_2/explore_visualizer.py:664: UserWarning:

Disadvantage Zone Average Travel Time per Person by Auto 0 not in data


VBox(children=(HBox(children=(VBox(children=(Dropdown(index=1, options=('None', 'Explore'), value='Explore'), …

In [36]:
viz.selection_feature_scores()

/Users/wsp/.cache/uv/archive-v0/iAbowDKd3Wpw0B_RdjZ32/lib/python3.9/site-packages/jupyter_client/session.py:721: UserWarning:

Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant

/Users/wsp/.cache/uv/archive-v0/iAbowDKd3Wpw0B_RdjZ32/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning:

urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020

FigureWidget({
    'data': [{'marker': {'color': 'rgb(255, 127, 14)'},
              'orientation': 'h',
              'text': [N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A],
              'textposition': 'outside',
              'texttemplate': '%{text}',
              'type': 'bar',
              'uid': 'e15d256c-36b6-4884-b4fa-ee4ee89315f7',
              'x': [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
              'y': [HH_EMP_Growth, HH_EMP_Distribution, AV_Rates, EV_Rates,
                    Teleworking, Heavy_Medium_Truck_Travel, Ecommerce,
                    Transit_Headways, Transit_Service_Expansion,
                    Roadway_Capacity_Improvement, Road_User_Fee,
                    Incentives_Special_AreaPop]}],
    'layout': {'height': 264,
               'margin': {'b': 0, 'l': 0, 'r': 0, 't': 0},
               'template': '...',
               'yaxis': {'autorange': 'reversed'}}
})

In [37]:
viz.two_way()

TwoWayFigure(children=(FigureWidget({
    'data': [{'hovertemplate': ('%{xaxis.title.text}: %{x}<br>%' ... 'tr…

In [38]:
viz.three_way()

ThreeWayFigure(children=(FigureWidget({
    'data': [{'hovertemplate': ('Autonomous Vehicle Adoption Ra' ... '…

In [39]:
viz.splom(
         rows=('Regional VMT', 'Regional VHT'),
         cols='L',
         )

FigureWidget({
    'data': [{'hovertemplate': ('<b>Regional VMT</b>: %{y}<br><' ... 'tra>experiment %{meta}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([0, 1, 2, ..., 9997, 9998, 9999], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': '7d935f62-ccd4-48cc-bd3a-664ab66e86c0',
              'x': {'bdata': ('jUwoAjcu9z8eFtiC3NTxPyKSLAK6X/' ... 'DfGS3mP+7WhSWdm+Q/lwhRrZ7t4D8='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'y': {'bdata': ('NkWUM8/sdkE34hYwIYl3QWTHWxE6BX' ... 'zXyq57QVcPi/QFKXlBaP+MiEroeUE='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': ('<b>Regional VMT</b>: %{meta[1]' ... '>experiment %{meta[0]}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([[0, 24038643.223698817, 'No-Expansion'],
                             [1, 24678931.00558683, 'No-Expansion'],
                             [2, 26235809.08490695, 'No-Expansion'],
                             ...,
                             [9997, 29027501.456166312, 'Expansion'],
                             [9998, 26382431.283950176, 'No-Expansion'],
                             [9999, 27165864.534423262, 'No-Expansion']], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': 'ff07644f-014a-45f5-b734-acc87673c2cb',
              'x': {'bdata': ('ASNA2K+yzr9AAq08iBRzv+q33Hv9VL' ... 'RMQjHyP9AjxvpQoJc/lCYlgbvoyj8='),
                    'dtype': 'f8'},
              'xaxis': 'x2',
              'y': {'bdata': ('NkWUM8/sdkE34hYwIYl3QWTHWxE6BX' ... 'zXyq57QVcPi/QFKXlBaP+MiEroeUE='),
                    'dtype': 'f8'},
              'yaxis': 'y2'},
             {'hovertemplate': ('<b>Regional VMT</b>: %{meta[1]' ... '>experiment %{meta[0]}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([[0, 24038643.223698817, 'All'],
                             [1, 24678931.00558683, 'High and Medium'],
                             [2, 26235809.08490695, 'High and Medium'],
                             ...,
                             [9997, 29027501.456166312, 'High'],
                             [9998, 26382431.283950176, 'High'],
                             [9999, 27165864.534423262, 'All']], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': '61b796fb-d8c1-4a17-b89c-eb5904094954',
              'x': {'bdata': ('me6TNrtaAUDQwDz0DiXzPyIeUboAP/' ... 'bjZb6lvxyWosRzvbO/JVItkl+TAUA='),
                    'dtype': 'f8'},
              'xaxis': 'x3',
              'y': {'bdata': ('NkWUM8/sdkE34hYwIYl3QWTHWxE6BX' ... 'zXyq57QVcPi/QFKXlBaP+MiEroeUE='),
                    'dtype': 'f8'},
              'yaxis': 'y3'},
             {'hovertemplate': ('<b>Regional VMT</b>: %{y}<br><' ... 'tra>experiment %{meta}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([0, 1, 2, ..., 9997, 9998, 9999], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': '001f91da-d051-4e3f-acbe-544e602042f1',
              'x': {'bdata': ('U02Hr1EhqT9PSgHnLjmiP0sPYrVGn6' ... 'l3Uz6rP1rUB29O0JE/sJMc2jSctT8='),
                    'dtype': 'f8'},
              'xaxis': 'x4',
              'y': {'bdata': ('NkWUM8/sdkE34hYwIYl3QWTHWxE6BX' ... 'zXyq57QVcPi/QFKXlBaP+MiEroeUE='),
                    'dtype': 'f8'},
              'yaxis': 'y4'},
             {'hovertemplate': ('<b>Regional VMT</b>: %{y}<br><' ... 'tra>experiment %{meta}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([0, 1, 2, ..., 9997, 9998, 9999], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': '7605f924-0353-43cb-9e7b-8b8f3d5e20b0',
              'x': {'bdata': ('zJVzdHfUwD9e9JY62cvQP9BNSfDm0b' ... '5rm07YPyDjdKBIrd4/knHtk8kdvz8='),
                    'dtype': 'f8'},
              'xaxis': 'x5',
              'y': {'bdata': ('NkWUM8/sdkE34hYwIYl3QWTHWxE6BX' ... 'zXyq57QVcPi/QFKXlBaP+MiEroeUE='),
                    'dtype': 'f8'},
              'yaxis': 'y5'},
             {'hovertemplate': ('<b>Regional VHT</b>: %{y}<br><' ... 'tra>experiment %{meta}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([0, 1, 2, ..., 9997, 9998, 9999], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': 'd22b5590-ec7a-4dc8-8781-ab772907835e',
              'x': {'bdata': ('jUwoAjcu9z8eFtiC3NTxPyKSLAK6X/' ... 'DfGS3mP+7WhSWdm+Q/lwhRrZ7t4D8='),
                    'dtype': 'f8'},
              'xaxis': 'x6',
              'y': {'bdata': ('G7UFp0NdIkG4sXDKt78jQSVMEuUQ6S' ... 'hvIqYlQSlCI41nwSVBC7Hvs2GrIkE='),
                    'dtype': 'f8'},
              'yaxis': 'y6'},
             {'hovertemplate': ('<b>Regional VHT</b>: %{meta[1]' ... '>experiment %{meta[0]}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([[0, 601761.8262154193, 'No-Expansion'],
                             [1, 647131.8953910386, 'No-Expansion'],
                             [2, 586888.4474052234, 'No-Expansion'],
                             ...,
                             [9997, 709393.218204619, 'Expansion'],
                             [9998, 712883.7756596255, 'No-Expansion'],
                             [9999, 611760.8514380766, 'No-Expansion']], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': '3d79aa2d-fc09-47e4-9f4e-35355e88a727',
              'x': {'bdata': ('ASNA2K+yzr9AAq08iBRzv+q33Hv9VL' ... 'RMQjHyP9AjxvpQoJc/lCYlgbvoyj8='),
                    'dtype': 'f8'},
              'xaxis': 'x7',
              'y': {'bdata': ('G7UFp0NdIkG4sXDKt78jQSVMEuUQ6S' ... 'hvIqYlQSlCI41nwSVBC7Hvs2GrIkE='),
                    'dtype': 'f8'},
              'yaxis': 'y7'},
             {'hovertemplate': ('<b>Regional VHT</b>: %{meta[1]' ... '>experiment %{meta[0]}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([[0, 601761.8262154193, 'All'],
                             [1, 647131.8953910386, 'High and Medium'],
                             [2, 586888.4474052234, 'High and Medium'],
                             ...,
                             [9997, 709393.218204619, 'High'],
                             [9998, 712883.7756596255, 'High'],
                             [9999, 611760.8514380766, 'All']], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': '534ce478-c847-4304-8141-6a71990af43f',
              'x': {'bdata': ('me6TNrtaAUDQwDz0DiXzPyIeUboAP/' ... 'bjZb6lvxyWosRzvbO/JVItkl+TAUA='),
                    'dtype': 'f8'},
              'xaxis': 'x8',
              'y': {'bdata': ('G7UFp0NdIkG4sXDKt78jQSVMEuUQ6S' ... 'hvIqYlQSlCI41nwSVBC7Hvs2GrIkE='),
                    'dtype': 'f8'},
              'yaxis': 'y8'},
             {'hovertemplate': ('<b>Regional VHT</b>: %{y}<br><' ... 'tra>experiment %{meta}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([0, 1, 2, ..., 9997, 9998, 9999], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': '8957f50f-4d9f-416d-a3f1-017c6e8eac39',
              'x': {'bdata': ('U02Hr1EhqT9PSgHnLjmiP0sPYrVGn6' ... 'l3Uz6rP1rUB29O0JE/sJMc2jSctT8='),
                    'dtype': 'f8'},
              'xaxis': 'x9',
              'y': {'bdata': ('G7UFp0NdIkG4sXDKt78jQSVMEuUQ6S' ... 'hvIqYlQSlCI41nwSVBC7Hvs2GrIkE='),
                    'dtype': 'f8'},
              'yaxis': 'y9'},
             {'hovertemplate': ('<b>Regional VHT</b>: %{y}<br><' ... 'tra>experiment %{meta}</extra>'),
              'marker': {'color': array(['rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)', ...,
                                         'rgb(255, 127, 14)', 'rgb(255, 127, 14)', 'rgb(255, 127, 14)'],
                                        dtype=object),
                         'opacity': {'bdata': ('mpmZmZmZuT+amZmZmZm5P5qZmZmZmb' ... 'mZmZm5P5qZmZmZmbk/mpmZmZmZuT8='),
                                     'dtype': 'f8'},
                         'size': 3},
              'meta': array([0, 1, 2, ..., 9997, 9998, 9999], dtype=object),
              'mode': 'markers',
              'showlegend': False,
              'type': 'scattergl',
              'uid': '588d54f6-6bcb-4e17-98e4-855aa6ed1bde',
              'x': {'bdata': ('zJVzdHfUwD9e9JY62cvQP9BNSfDm0b' ... '5rm07YPyDjdKBIrd4/knHtk8kdvz8='),
                    'dtype': 'f8'},
              'xaxis': 'x10',
              'y': {'bdata': ('G7UFp0NdIkG4sXDKt78jQSVMEuUQ6S' ... 'hvIqYlQSlCI41nwSVBC7Hvs2GrIkE='),
                    'dtype': 'f8'},
              'yaxis': 'y10'}],
    'layout': {'height': 375,
               'margin': {'b': 10, 'l': 10, 'r': 10, 't': 10},
               'meta': {'cols': [Transit_Headways, Transit_Service_Expansion,
                                 Roadway_Capacity_Improvement, Road_User_Fee,
                                 Incentives_Special_AreaPop],
                        'marker_size': 3,
                        'mass': 250,
                        'refpoint': {},
                        'row_titles': 'side',
                        'rows': [Regional VMT, Regional VHT],
                        'selected_color': 'rgb(255, 127, 14)',
                        'size': 150,
                        'unselected_color': 'rgb(31, 119, 180)',
                        'use_gl': True},
               'plot_bgcolor': '#E5ECF6',
               'template': '...',
               'width': 850,
               'xaxis': {'anchor': 'y', 'domain': [0.0, 0.184], 'matches': 'x6', 'showticklabels': False},
               'xaxis10': {'anchor': 'y10',
                           'domain': [0.816, 1.0],
                           'range': [-0.034981920419409514, 0.5349791916412678],
                           'title': {'text': 'Ⓛ Incentives for<br>special are<br>population'}},
               'xaxis2': {'anchor': 'y2', 'domain': [0.204, 0.388], 'matches': 'x7', 'showticklabels': False},
               'xaxis3': {'anchor': 'y3', 'domain': [0.408, 0.592], 'matches': 'x8', 'showticklabels': False},
               'xaxis4': {'anchor': 'y4', 'domain': [0.6120000000000001, 0.796], 'matches': 'x9', 'showticklabels': False},
               'xaxis5': {'anchor': 'y5', 'domain': [0.816, 1.0], 'matches': 'x10', 'showticklabels': False},
               'xaxis6': {'anchor': 'y6',
                          'domain': [0.0, 0.184],
                          'range': [0.3951491492645803, 2.1049190364168906],
                          'title': {'text': 'Ⓛ Transit headways'}},
               'xaxis7': {'anchor': 'y7',
                          'domain': [0.204, 0.388],
                          'range': [-0.5480198019801981, 1.548019801980198],
                          'tickmode': 'array',
                          'ticktext': [No-Expansion, Expansion],
                          'tickvals': [0, 1],
                          'title': {'text': 'Ⓛ Transit Service<br>Expansion'}},
               'xaxis8': {'anchor': 'y8',
                          'domain': [0.408, 0.592],
                          'range': [-0.5480198019801981, 2.548019801980198],
                          'tickmode': 'array',
                          'ticktext': [High, High and Medium, All],
                          'tickvals': [0, 1, 2],
                          'title': {'text': 'Ⓛ Roadway Capacity<br>Improvements'}},
               'xaxis9': {'anchor': 'y9',
                          'domain': [0.6120000000000001, 0.796],
                          'range': [-0.006990844995962789, 0.10699689221490985],
                          'title': {'text': 'Ⓛ Road User Fee'}},
               'yaxis': {'anchor': 'x',
                         'domain': [0.525, 1.0],
                         'range': [16887039.206602093, 34787873.0083072],
                         'title': {'text': 'Ⓜ Regional VMT'}},
               'yaxis10': {'anchor': 'x10', 'domain': [0.0, 0.475], 'matches': 'y6', 'showticklabels': False},
               'yaxis2': {'anchor': 'x2', 'domain': [0.525, 1.0], 'matches': 'y', 'showticklabels': False},
               'yaxis3': {'anchor': 'x3', 'domain': [0.525, 1.0], 'matches': 'y', 'showticklabels': False},
               'yaxis4': {'anchor': 'x4', 'domain': [0.525, 1.0], 'matches': 'y', 'showticklabels': False},
               'yaxis5': {'anchor': 'x5', 'domain': [0.525, 1.0], 'matches': 'y', 'showticklabels': False},
               'yaxis6': {'anchor': 'x6',
                          'domain': [0.0, 0.475],
                          'range': [333690.6064271966, 945089.2750129304],
                          'title': {'text': 'Ⓜ Regional VHT'}},
               'yaxis7': {'anchor': 'x7', 'domain': [0.0, 0.475], 'matches': 'y6', 'showticklabels': False},
               'yaxis8': {'anchor': 'x8', 'domain': [0.0, 0.475], 'matches': 'y6', 'showticklabels': False},
               'yaxis9': {'anchor': 'x9', 'domain': [0.0, 0.475], 'matches': 'y6', 'showticklabels': False}}
})